GM:OnContextMenuOpen()
GM:OnContextMenuClose()
GM:LoadLiliaFonts(font, genericFont)
GM:CreateLoadingScreen()
GM:ShouldCreateLoadingScreen()
GM:InitializedConfig()
GM:CharacterListLoaded()
GM:InitPostEntity()
GM:CalcView(client, origin, angles, fov)
GM:HUDPaintBackground()
GM:ShouldDrawEntityInfo(entity)
GM:PlayerBindPress(client, bind, pressed)
GM:ItemShowEntityMenu(entity)
GM:SetupQuickMenu(menu)
GM:DrawLiliaModelView(panel, ent)
GM:ScreenResolutionChanged(oldW, oldH)
GM:LiliaLoaded()
GM:PlayerNoClip(client)
GM:TranslateActivity(client, act)
GM:DoAnimationEvent(client, event, data)
GM:EntityEmitSound(data)
GM:HandlePlayerLanding(client, velocity, wasOnGround)
GM:CalcMainActivity(client, velocity)
GM:OnCharVarChanged(char, varName, oldVar, newVar)
GM:GetDefaultCharName(client, faction)
GM:GetDefaultCharDesc(client, faction)
GM:CanPlayerUseChar(client, char)
GM:CheckFactionLimitReached(faction, character, client)
GM:CanProperty(client, property, entity)
GM:PhysgunPickup(client, entity)
GM:Move(client, moveData)
GM:CanItemBeTransfered(itemObject, curInv, inventory)
GM:SetupBotCharacter(client)
GM:SetupBotInventory(client, character)
GM:PlayerInitialSpawn(client)
GM:PlayerUse(client, entity)
GM:KeyPress(client, key)
GM:KeyRelease(client, key)
GM:CanPlayerDropItem(client, item)
GM:CanPlayerInteractItem(client, action, item)
GM:CanPlayerTakeItem(client, item)
GM:PlayerShouldTakeDamage(client, attacker)
GM:EntityTakeDamage(entity, dmgInfo)
GM:PrePlayerLoadedChar(client, character, lastChar)
GM:PlayerLoadedChar(client, character, lastChar)
GM:CharacterLoaded(id)
GM:PlayerSay(client, message)
GM:PlayerSpawn(client)
GM:PlayerSpawnNPC(client, npcType, weapon)
GM:PlayerSpawnSWEP(client, weapon, info)
GM:PlayerSpawnProp(client)
GM:PlayerSpawnRagdoll(client)
GM:PlayerSpawnVehicle(client, model, name, data)
GM:PlayerLoadout(client)
GM:PostPlayerLoadout(client)
GM:PlayerDeath(client, inflictor, attacker)
GM:PlayerHurt(client, attacker, health, damage)
GM:PlayerDeathThink(client)
GM:PlayerDisconnected(client)
GM:PlayerAuthed(client, steamID, uniqueID)
GM:InitPostEntity()
GM:ShutDown()
GM:PlayerDeathSound()
GM:InitializedSchema()
GM:PlayerCanHearPlayersVoice(listener, speaker)
GM:OnPhysgunFreeze(weapon, physObj, entity, client)
GM:CanPlayerSuicide(client)
GM:AllowPlayerPickup(client, entity)
GM:PreCleanupMap()
GM:PostCleanupMap()
GM:CharacterPreSave(character)
GM:OnServerLog(client, logType, ...)
GM:GetPreferredCarryAngles(entity)
GM:InitializedPlugins()
GM:CreateDefaultInventory(character)
GM:LiliaTablesLoaded()
GM:PluginShouldLoad(plugin)
GM:GetSalaryInterval(client, faction)
GM:CreateSalaryTimer(client)
GM:GetGameDescription()
GM:OnPlayerJoinClass(client, class, oldClass)
GM:OnPickupMoney(client, moneyEntity)
GM:PlayerAuthed(client, steamID, uniqueID)
GM:SetupDatabase()
GM:OnMySQLOOConnected()
GM:RegisterPreparedStatements()
GM:Initialize()
GM:OnReloaded()