ITEM.name = "Ellipsoid Metal"
ITEM.desc = "A Zero Factory item"
ITEM.model = "models/props_combine/breenlight.mdl"
ITEM.color = Color(255, 255, 255, 255)
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 43
