ITEM.name = "Red Chip"
ITEM.desc = "A Zero Factory item"
ITEM.model = "models/zerochain/props_factory/zpf_chip.mdl"
ITEM.color = Color(211, 85, 255, 82)
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 22
