ITEM.name = "Satellite - MK1"
ITEM.desc = "A Zero Factory item"
ITEM.model = "models/zerochain/props_factory/zpf_satelity01.mdl"
ITEM.color = Color(255, 57, 255, 216)
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 28
