name: Lua Lint

on:
  push:
  pull_request:

jobs:
  lua-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: lilia

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: '5.2'

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luacheck

      - name: Run Lua lint
        run: |
          ls
          cd lilia
          luacheck . --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length
          cd ..
          ls
