name: CI
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: helix

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.2"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Pull gluacheck
      uses: actions/checkout@v2
      with:
        repository: impulsh/gluacheck
        path: luacheck

    - name: Build gluacheck
      working-directory: luacheck
      run: luarocks make

    - name: Lint
      working-directory: helix
      run: luacheck . --no-unused-secondaries --no-unused-args --no-redefined --no-unused --no-global --no-self -i 4.2/.*_ --formatter visual_studio --no-unused --no-max-line-length  --no-max-code-line-length --no-max-string-line-length  --no-max-comment-line-length --no-max-cyclomatic-complexity
