name: Commit Verification and Wiki Update

on:
  push:
  pull_request:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  CodeVerifierAndIndenter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: lilia
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: '5.2'
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Pull gluacheck
        uses: actions/checkout@v2
        with:
          repository: impulsh/gluacheck
          path: luacheck
      - name: Build gluacheck
        working-directory: luacheck
        run: luarocks make
      - name: Lint with gluacheck
        working-directory: lilia
        run: >-
          luacheck . --no-unused-secondaries --no-unused-args --no-redefined
          --no-unused --no-global --no-self -i 4.2/.*_ --formatter visual_studio
          --no-unused --no-max-line-length --no-max-code-line-length
          --no-max-string-line-length --no-max-comment-line-length
          --no-max-cyclomatic-complexity 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Bash
        run: |
          sudo apt update
          sudo apt install -y unzip
        shell: bash
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Wiki
        uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: development/documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
