name: Publish wiki

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Wiki
        uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
